

---


# **Data Science and Machine Learning for Environmental Engineering**


---



---
# **Module 4**
---

## Before we start

![Data Science *Workflow*](https://www.tutorialspoint.com/google_colab/images/saving_google_drive.jpg)

In [ ]:
#import pandas as pd; df=pd.read_csv('https://ckan-data.montevideo.gub.uy/dataset/92121547-888b-417e-b0e1-2899f707a4fa/resource/ecb68681-9eb2-45b5-97af-dcf95f4e7a53/download/monitoreo_de_calidad_de_cuerpos_de_agua.csv');df

---
## Representing Data in Python
---


![](https://lh7-us.googleusercontent.com/NmIOeli9FXWpUfvcEhOH7PsLJxgivD3TIKb61xpaxG0nATY7pBOxTDY1WnkgbFuXxOBYDrNbfgmnd30IJWzJ9CCQ9xz-BLF1Blt5FHmbizPVcgwYAvwJ4rB2H482C9lEl4-0uUGj13o-64QEY1iuLMo)


### Introduction

Python is a versatile, beginner-friendly programming language known for its simplicity and readability. It is widely used in various fields such as web development, data analysis, artificial intelligence, and more. Python’s syntax is designed to be intuitive, making it an excellent choice for those new to programming.


![](https://flink.apache.org/img/blog/2020-08-04-pyflink-pandas/python-scientific-stack.png)

In [1]:
# 1. Printing Output
print("Hello, World!")  # This prints "Hello, World!" to the console.

Hello, World!


In [2]:
# 2. Variables and Data Types
name = "Alice"    # String
age = 25          # Integer
height = 5.6      # Float
is_student = True # Boolean

print(name, age, height, is_student)  # Displaying the variables

Alice 25 5.6 True


In [4]:
# 3. Basic Arithmetic Operations
a = 10
b = 3

print(a + b)  # Addition: 13
print(a - b)  # Subtraction: 7
print(a * b)  # Multiplication: 30
print(a / b)  # Division: 3.333...
print(a % b)  # Modulus (remainder): 1

13
7
30
3.3333333333333335
1


In [6]:
# 4. Conditional Statements
age = 16

if age >= 18:
    print("You are an adult.")
else:
    print("You are a minor.")

You are a minor.


In [8]:
# 5. Loops
# for Loop Example
for i in range(5):  # Loops from 0 to 4
    print("Iteration:", i)


Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4


In [9]:
# while Loop Example
count = 0
while count < 3:
    print("Count:", count)
    count += 1  # Increment count by 1
    #count = count + 1

Count: 0
Count: 1
Count: 2


In [11]:
# 6. Functions
def greet(name):
    """This function greets the person passed in as a parameter."""
    print("Hello,", name)

greet("Alice")
greet("Bob")


Hello, Alice
Hello, Bob


In [12]:
# Additional Function Example: Factorial Calculation
def factorial_iterative(n):
    """Calculate factorial of a number using iteration."""
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

# Testing the factorial functions
number = 5
print(f"\nFactorial of {number} (Iterative):", factorial_iterative(number))


Factorial of 5 (Iterative): 120


In [16]:
# 7. List Operations
# Lists are ordered, mutable collections of items.
fruits = ["apple", "banana", "cherry"]

# Accessing elements
print(fruits[0])  # Output: apple
print(fruits[-1]) # Output: cherry (last element)
print(fruits[-2]) # Output: cherry (last element)


apple
cherry
banana


In [17]:
# Adding elements
fruits.append("orange")  # Adds "orange" to the end
print(fruits)  # Output: ['apple', 'banana', 'cherry', 'orange']


['apple', 'banana', 'cherry', 'orange']


In [18]:

# Removing elements
fruits.remove("banana")  # Removes "banana"
print(fruits)  # Output: ['apple', 'cherry', 'orange']


['apple', 'cherry', 'orange']


In [21]:
['apple', 'banana'] + ['cherry', 'orange']

['apple', 'banana', 'cherry', 'orange']

In [22]:
# Iterating through a list
for fruit in fruits:
    print(fruit)

apple
cherry
orange



NumPy (Numerical Python) is for numerical computations.

* **Arrays:** NumPy's ndarray is a multi-dimensional, homogeneous array.
* **Efficiency:** NumPy arrays are faster than Python lists for numerical operations.
* **Mathematical Functions:** NumPy offers functions for array operations, linear algebra, and statistics.


```python
import numpy as np

array = np.array([1, 2, 3, 4, 5])
print(array)
mean = np.mean(array)
print(mean)

In [23]:
# 8. NumPy Basics
# NumPy is a powerful library for numerical computations in Python.

import numpy as np

# Creating a NumPy array
array = np.array([1, 2, 3, 4, 5])
print("\nNumPy Array:", array)


NumPy Array: [1 2 3 4 5]


In [24]:
[1, 2, 3, 4, 5]+[1, 2, 3, 4, 5]


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [25]:
array + array

array([ 2,  4,  6,  8, 10])

In [26]:
# Performing operations on arrays
print("Array squared:", array ** 2)  # Squares each element
print("Array sum:", np.sum(array))   # Calculates the sum of all elements


Array squared: [ 1  4  9 16 25]
Array sum: 15


In [27]:
# Creating a 2D array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array (Matrix):")
print(matrix)



2D Array (Matrix):
[[1 2 3]
 [4 5 6]]


In [28]:
# Matrix multiplication
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[2, 0], [1, 3]])
result = np.dot(matrix_a, matrix_b)
print("\nMatrix Multiplication Result:")
print(result)


Matrix Multiplication Result:
[[ 4  6]
 [10 12]]


In [29]:
# Array operations
array = np.array([1, 2, 3, 4, 5])
print(array)
mean = np.mean(array)
print(mean)

[1 2 3 4 5]
3.0


--
## Introduction to Pandas

### What is Pandas?

Pandas is a powerful and flexible Python library for data manipulation and analysis.
It provides data structures and functions designed to make working with structured data easy and intuitive.
Built on top of NumPy, Pandas leverages its efficiency for numerical operations.
Essentially, Pandas brings the power of spreadsheets and relational databases to Python.

### Key Features

* Data Structures:
    * Series: One-dimensional labeled array, similar to a column in a spreadsheet or a NumPy array with labels.
    * DataFrame: Two-dimensional labeled data structure, like a table or spreadsheet, with columns of potentially different data types.
* Data Manipulation: Offers functions for filtering, sorting, grouping, merging, and reshaping data.

### Pandas in Action

* Pandas is used for:
    * Data cleaning and preprocessing.
    * Exploratory data analysis (EDA).
    * Data visualization.
    * Statistical analysis.
    * Building machine learning pipelines.



---
## Pandas Tutorial: Analyzing Environmental Complaints Data from Uruguay
---

### Introduction

The dataset used in this tutorial is sourced from the [Uruguayan Open Data Portal](https://catalogodatos.gub.uy/dataset/ministerio-de-ambiente-denuncias-ambientales). It contains information about **environmental complaints** submitted to the Ministry of Environment in Uruguay.

#### The Problem

Environmental complaints are critical for addressing issues such as:
- Pollution
- Illegal dumping
- Deforestation
- Other environmental violations

However:
- Raw data is often messy and unstructured.
- Insights are hidden without proper cleaning and analysis.


---


##Exploratory Task: Analyze Environmental Complaint Trends

###Objective
Perform exploratory data analysis (EDA) to answer the following questions:

1. What are the most common types of environmental complaints?
2. Which departments (regions) receive the highest number of complaints?
3. How have the number of complaints changed over time (e.g., monthly or yearly trends)?
4. ...

In [32]:
## Step 1: Install and Import Libraries

import pandas as pd

In [35]:
import pandas as pd

# Load the dataset
url = "https://catalogodatos.gub.uy/dataset/14c95c50-3aac-475a-92d1-26d2ddfb6fdc/resource/19911a59-e969-41be-8a09-65da6e4848bd/download/denuncias-ambientales.csv"
df = pd.read_csv(url)

# Data Science Challenge: **Water Quality Monitoring in Uruguay**

## Dataset Overview

The dataset provided at the link ([Water Quality Monitoring](https://catalogodatos.gub.uy/dataset/monitoreo-de-calidad-en-los-cuerpos-de-agua/resource/ecb68681-9eb2-45b5-97af-dcf95f4e7a53)) contains information about water quality monitoring in various water bodies across Uruguay. It includes parameters such as:

- **Location**: Geographic details of the water body.
- **Date**: The date of the measurement.
- **Water Quality Parameters**: Metrics like pH, dissolved oxygen, turbidity, temperature, and other indicators of water quality.
- **Pollutants**: Levels of contaminants or pollutants (e.g., nitrates, phosphates, heavy metals).
- **Compliance Status**: Whether the water body meets environmental quality standards.

This dataset is ideal for exploring real-world environmental issues and applying data science techniques to analyze and address them.

---

## Challenge: Predicting Water Quality and Identifying Pollution Hotspots

### **Objective**
You will use the dataset to perform exploratory data analysis (EDA), build predictive models, and propose actionable solutions to improve water quality and protect ecosystems.

---

## Step-by-Step Plan

### 1. Initial Exploration: Understand the Data

Start by loading and inspecting the dataset. Pose the following questions to guide students:

- What are the key features in the dataset? Are there missing values or inconsistencies?
- What is the distribution of water quality parameters (e.g., pH, dissolved oxygen)?
- How many water bodies are included, and where are they located?

**Tasks:**
- Load the dataset into a Pandas DataFrame.
- Perform basic EDA: Check for missing values, data types, and summary statistics.
- Visualize the geographic distribution of water bodies using libraries like `matplotlib` or `plotly`.

---

### 2. Investigate Water Quality Trends

Students should to explore temporal and spatial trends in water quality.

#### Questions to Solve:
- Are there seasonal patterns in water quality parameters (e.g., higher turbidity during rainy seasons)?
- How do water quality metrics vary across different regions or water bodies?
- Which water bodies consistently fail to meet environmental standards?

**Tasks:**
- Group the data by date (month/year) and calculate average water quality metrics.
- Create time-series plots for key parameters (e.g., pH, dissolved oxygen).
- Identify water bodies with poor compliance rates and visualize them on a map.

---

### 3. Identify Pollution Hotspots

Identify areas with high levels of pollutants or poor water quality.

#### Questions to Solve:
- Which water bodies have the highest levels of contaminants (e.g., nitrates, phosphates)?
- Are there correlations between specific pollutants and water quality parameters (e.g., low dissolved oxygen and high turbidity)?
- Can you cluster water bodies based on their pollution levels?

**Tasks:**
- Calculate descriptive statistics for pollutant levels.
- Use correlation matrices and heatmaps to explore relationships between variables.
- Apply clustering algorithms (e.g., K-Means) to group water bodies based on pollution levels.

---

### 4. Build Predictive Models

Challenge: to predict water quality outcomes or compliance status using machine learning.

#### Questions to Solve:
- Can we predict whether a water body will meet environmental standards based on its water quality parameters?
- Which factors are most predictive of poor water quality?
- How accurate are the predictions, and what can we learn from the model's results?

**Tasks:**
- Preprocess the data: Handle missing values, encode categorical variables, and normalize numerical features.
- Train classification models (e.g., Logistic Regression, Random Forest) to predict compliance status.
- Evaluate model performance using metrics like accuracy, precision, recall, and F1-score.

---

### 5. Propose Solutions

Finally,  propose actionable solutions based on their findings.

#### Questions to Solve:
- What interventions could improve water quality in the most polluted areas?
- How can policymakers use this data to prioritize resources for water quality monitoring?
- What recommendations would you make to prevent future pollution?

**Tasks:**
- Write a short report summarizing their findings and proposing solutions.
- Include visualizations and insights from their analysis to support their recommendations.
- Present their findings to the course supervisor.

---

## Sample Questions for Students

### Exploratory Analysis
1. What is the average pH level across all water bodies, and how does it vary by region?
2. Which water quality parameter shows the highest variability, and why might that be?
3. Are there any water bodies that consistently exceed acceptable pollutant levels?

### Trend Analysis
4. Do water quality parameters show any seasonal patterns? For example, is turbidity higher during the rainy season?
5. How has water quality changed over time in specific regions or water bodies?

### Pollution Hotspots
6. Can you identify clusters of water bodies with similar pollution levels?
7. Which pollutants are most strongly correlated with poor water quality?

### Predictive Modeling
8. Can you predict whether a water body will meet environmental standards based on its water quality metrics?
9. Which features are most important for predicting compliance status?

### Actionable Insights
10. Based on your analysis, which water bodies should receive priority for cleanup efforts?
11. What policies or interventions would you recommend to improve water quality?

---

## Deliverables

At the end of the challenge, students should submit:

1. A Jupyter Notebook containing their code, visualizations, and analysis.
2. A written report summarizing their findings and recommendations.
3. A presentation to share their insights with the class or stakeholders.

---

## Learning Outcomes


- Gain hands-on experience with real-world environmental data.
- Learn how to clean, preprocess, and analyze datasets using Python and Pandas.
- Develop skills in exploratory data analysis, visualization, and machine learning.
- Practice translating data-driven insights into actionable solutions.
- Critical thinking and problem-solving in the context of environmental sustainability. 🌍